# Generated by Django 5.2.17 on 2026-09-15 05:02

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document_number', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('change_customer_status', 'Can change customer status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='partners_customer_name_not_blank'), models.CheckConstraint(condition=models.Q(('document_number', ''), models.Q(('document_number__regex', '^\\s*$'), _negated=True), _connector='OR'), name='partners_customer_document_valid'), models.UniqueConstraint(django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('document_number')), condition=models.Q(('document_number', ''), _negated=True), name='partners_customer_document_ci_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(blank=True, default='', max_length=30)),
                ('contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('change_supplier_status', 'Can change supplier status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='partners_supplier_name_not_blank'), models.CheckConstraint(condition=models.Q(('tax_id', ''), models.Q(('tax_id__regex', '^\\s*$'), _negated=True), _connector='OR'), name='partners_supplier_tax_id_valid'), models.UniqueConstraint(django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('tax_id')), condition=models.Q(('tax_id', ''), _negated=True), name='partners_supplier_tax_id_ci_uniq')],
            },
        ),
    ]
