# Generated by Django 5.2.17 on 2026-09-15 05:02

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('location_type', models.CharField(choices=[('BRANCH', 'Sucursal'), ('WAREHOUSE', 'Almacén')], max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'code'],
                'permissions': [('change_location_status', 'Can change location status')],
                'indexes': [models.Index(fields=['location_type', 'is_active'], name='inv_location_type_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^\\s*$'), _negated=True), name='inventory_location_code_not_blank'), models.UniqueConstraint(django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('code')), name='inventory_location_code_ci_uniq'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='inventory_location_name_not_blank'), models.CheckConstraint(condition=models.Q(('location_type__in', ('BRANCH', 'WAREHOUSE'))), name='inventory_location_type_valid')],
            },
        ),
    ]
