# Generated by Django 5.2.17 on 2026-09-15 05:02

import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('change_category_status', 'Can change category status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='catalog_category_name_not_blank'), models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='catalog_category_name_ci_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_of_measure', models.CharField(choices=[('UNIT', 'Unidad'), ('KILOGRAM', 'Kilogramo'), ('GRAM', 'Gramo'), ('LITER', 'Litro'), ('MILLILITER', 'Mililitro'), ('METER', 'Metro'), ('CENTIMETER', 'Centímetro'), ('BOX', 'Caja'), ('PACKAGE', 'Paquete')], default='UNIT', max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name', 'sku'],
                'permissions': [('change_product_status', 'Can change product status')],
                'indexes': [models.Index(fields=['category', 'is_active'], name='cat_product_cat_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sku__regex', '^\\s*$'), _negated=True), name='catalog_product_sku_not_blank'), models.UniqueConstraint(django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('sku')), name='catalog_product_sku_ci_uniq'), models.CheckConstraint(condition=models.Q(('barcode', ''), models.Q(('barcode__regex', '^\\s*$'), _negated=True), _connector='OR'), name='catalog_product_barcode_valid'), models.UniqueConstraint(django.db.models.functions.text.Trim('barcode'), condition=models.Q(('barcode', ''), _negated=True), name='catalog_product_barcode_uniq'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='catalog_product_name_not_blank'), models.CheckConstraint(condition=models.Q(('sale_price__gte', Decimal('0'))), name='catalog_product_sale_price_nonnegative'), models.CheckConstraint(condition=models.Q(('unit_of_measure__in', ('UNIT', 'KILOGRAM', 'GRAM', 'LITER', 'MILLILITER', 'METER', 'CENTIMETER', 'BOX', 'PACKAGE'))), name='catalog_product_unit_valid')],
            },
        ),
    ]
